COMMANDS = {
    "/list": {
        "description": "List all files in the repository",
        "usage": "/list",
        "category": "Repository",
        "dangerous": False,
        "requires_write": False,
    },
    "/tree": {
        "description": "Show directory tree (optional depth)",
        "usage": "/tree [depth]",
        "category": "Repository",
        "dangerous": False,
        "requires_write": False,
    },
    "/find": {
        "description": "Find a file by name",
        "usage": "/find <file>",
        "category": "Repository",
        "dangerous": False,
        "requires_write": False,
    },
    "/open": {
        "description": "Open and display a file",
        "usage": "/open <file>",
        "category": "Repository",
        "dangerous": False,
        "requires_write": False,
    },
    "/search": {
        "description": "Search project files",
        "usage": "/search <query>",
        "category": "Repository",
        "dangerous": False,
        "requires_write": False,
    },
    "/summary": {
        "description": "Show repository summary",
        "usage": "/summary",
        "category": "Repository",
        "dangerous": False,
        "requires_write": False,
    },
    "/stats": {
        "description": "Display project statistics",
        "usage": "/stats",
        "category": "Repository",
        "dangerous": False,
        "requires_write": False,
    },
    "/recent": {
        "description": "List recently modified files",
        "usage": "/recent [limit]",
        "category": "Repository",
        "dangerous": False,
        "requires_write": False,
    },
    "/todo": {
        "description": "Scan project for TODO/FIXME/HACK/BUG tags",
        "usage": "/todo",
        "category": "Repository",
        "dangerous": False,
        "requires_write": False,
    },
    "/create": {
        "description": "Create an empty file",
        "usage": "/create <path>",
        "category": "Modification",
        "dangerous": True,
        "requires_write": True,
    },
    "/mkdir": {
        "description": "Create a directory",
        "usage": "/mkdir <path>",
        "category": "Modification",
        "dangerous": True,
        "requires_write": True,
    },
    "/write": {
        "description": "Write content to a file, overwriting existing content",
        "usage": "/write <path> <content>",
        "category": "Modification",
        "dangerous": True,
        "requires_write": True,
    },
    "/append": {
        "description": "Append content to a file",
        "usage": "/append <path> <content>",
        "category": "Modification",
        "dangerous": True,
        "requires_write": True,
    },
    "/replace": {
        "description": "Replace occurrences of old_text with new_text inside file",
        "usage": "/replace <path> <old_text> <new_text>",
        "category": "Modification",
        "dangerous": True,
        "requires_write": True,
    },
    "/delete": {
        "description": "Delete a file or directory",
        "usage": "/delete [--force] <path>",
        "category": "Modification",
        "dangerous": True,
        "requires_write": True,
    },
    "/move": {
        "description": "Move a file or directory to a new location",
        "usage": "/move <source> <destination>",
        "category": "Modification",
        "dangerous": True,
        "requires_write": True,
    },
    "/copy": {
        "description": "Copy a file or directory to a new location",
        "usage": "/copy <source> <destination>",
        "category": "Modification",
        "dangerous": True,
        "requires_write": True,
    },
    "/git-status": {
        "description": "Show current repository status",
        "usage": "/git-status",
        "category": "Git",
        "dangerous": False,
        "requires_write": False,
    },
    "/git-diff": {
        "description": "Show current working tree diff",
        "usage": "/git-diff",
        "category": "Git",
        "dangerous": False,
        "requires_write": False,
    },
    "/permission": {
        "description": "Change permission mode",
        "usage": "/permission",
        "category": "System",
        "dangerous": False,
        "requires_write": False,
    },
    "/display": {
        "description": "Change display mode",
        "usage": "/display",
        "category": "System",
        "dangerous": False,
        "requires_write": False,
    },
    "/help": {
        "description": "Show this help",
        "usage": "/help [command]",
        "category": "System",
        "dangerous": False,
        "requires_write": False,
    },
    "/exit": {
        "description": "Exit Scyther",
        "usage": "/exit",
        "category": "System",
        "dangerous": False,
        "requires_write": False,
    },
    "/where": {
        "description": "Locate symbol definitions",
        "usage": "/where <symbol>",
        "category": "Repository",
        "dangerous": False,
        "requires_write": False,
    },
    "/refs": {
        "description": "Locate symbol references/usages",
        "usage": "/refs <symbol>",
        "category": "Repository",
        "dangerous": False,
        "requires_write": False,
    },
    "/deps": {
        "description": "Show direct internal dependencies for a file",
        "usage": "/deps <path>",
        "category": "Repository",
        "dangerous": False,
        "requires_write": False,
    },
    "/largest": {
        "description": "Show largest files in repository",
        "usage": "/largest [limit]",
        "category": "Repository",
        "dangerous": False,
        "requires_write": False,
    },
    "/about": {
        "description": "Show general package information",
        "usage": "/about",
        "category": "Release",
        "dangerous": False,
        "requires_write": False,
    },
    "/version": {
        "description": "Display Scyther and Python version information",
        "usage": "/version",
        "category": "Release",
        "dangerous": False,
        "requires_write": False,
    },
    "/doctor": {
        "description": "Run diagnostic check rules on environment",
        "usage": "/doctor",
        "category": "Release",
        "dangerous": False,
        "requires_write": False,
    },
    "/config": {
        "description": "Display loaded config files and active settings",
        "usage": "/config",
        "category": "Release",
        "dangerous": False,
        "requires_write": False,
    },
}
